### ISSUE TITLE
Derive SwaggerResponseExampleAttribute from IFilterMetadata

### ISSUE THREAD

**Issue by RonakThakkar** [mattfrear/Swashbuckle.AspNetCore.Filters#121]
I have created a swagger custom example

public class UnauthorizedResponseExampleFilter : IExamplesProvider<string>
    {
        public string GetExamples()
        {
            return "You are required to provide a valid access token to access these API.";
        }
    }

Now I would like to register these for all controllers, so I would do something like 

            services.AddMvc(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                            .RequireAuthenticatedUser()
                            .Build();

                options.Filters.Add(new AuthorizeFilter(policy));

                options.Filters.Add(new ProducesResponseTypeAttribute((int)HttpStatusCode.OK));
                options.Filters.Add(new ProducesResponseTypeAttribute(typeof(string), (int)HttpStatusCode.Unauthorized));

                options.Filters.Add(new SwaggerResponseExampleAttribute((int)HttpStatusCode.Forbidden), typeof(UnauthorizedResponseExampleFilter));

            }).SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

However, these give compilation error and it will require that SwaggerResponseExampleAttribute is derived from IFilterMetadata the same as ProducesResponseTypeAttribute.

**Comment by mattfrear** [comment]
If all of your endpoints are secured, then ideally you should use something like:
`options.AddSecurityRequirement(` instead of `options.Filters.Add(new ProducesResponseTypeAttribute(typeof(string), (int)HttpStatusCode.Unauthorized));`

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements

I've also blogged a similar approach here:

https://mattfrear.com/2018/07/21/add-an-authorization-header-to-your-swagger-ui-with-swashbuckle-revisited/

**Comment by mattfrear** [comment]
Swashbuckle IOperationFilters are not IFilterMetadata, I'm not sure if it's even possible to implement, so I'm closing this.
