### ISSUE TITLE
Example response for different Accept media types

### ISSUE THREAD

**Issue by APIWT** [mattfrear/Swashbuckle.AspNetCore.Filters#129]
Hello!

I would love to be able to specify examples for accept media types other than `application/json`. For example, we have an endpoint that returns `application/json` by default but can also return `text/csv` by specifying the accept header. I'm not seeing a way with `[SwaggerResponseExample]` to handle this case.

Thank you!

**Comment by mattfrear** [comment]
Hi

I recently added support for XML media type examples, so it can be done.
Relevant line (for response examples):
https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/a5e370961ec7399486958d835f9f42b55d956d24/src/Swashbuckle.AspNetCore.Filters/Examples/ResponseExample.cs#L48

You're the second person to ask for CSV support:
https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/43

There's not a huge demand for CSV and it's not something I personally need, so I am not going to add code for it. But you are welcome to download my code and add CSV support, and if you are up for it, then submit a PR so that it gets added to the NuGet package.

**Comment by mattfrear** [comment]
This has been implemented and released 

https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/7.0.4
