### ISSUE TITLE
Inject different XmlSerializer

### ISSUE THREAD

**Issue by ArneD** [mattfrear/Swashbuckle.AspNetCore.Filters#136]
Currently the serialization of xml is done via the `XmlSerializer`. https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/44de94ab65eced060fefd1e50bb4b07527acccfc/src/Swashbuckle.AspNetCore.Filters/Extensions/ObjectExtensions.cs#L18

However a different serializer can be used, for example when using
```
services
  .AddMvcCore(...)
  .AddXmlDataContractSerializerFormatters()
```

Is it possible to inject the serializer for xml just as it's done for json?https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/ee8e231517f7052a96812d3cd9b4c8a8ef62572d/src/Swashbuckle.AspNetCore.Filters/Examples/ResponseExample.cs#L22

**Comment by CumpsD** [comment]
I noticed the JSON one comes from the ctor:

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/ee8e231517f7052a96812d3cd9b4c8a8ef62572d/src/Swashbuckle.AspNetCore.Filters/Examples/ResponseExample.cs#L18-L24

Which in turn is provided via DI:

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/44de94ab65eced060fefd1e50bb4b07527acccfc/src/Swashbuckle.AspNetCore.Filters/Extensions/ServiceCollectionExtensions.cs#L7-L12

@mattfrear, perhaps it is an option to replace the following with a Func?

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/ee8e231517f7052a96812d3cd9b4c8a8ef62572d/src/Swashbuckle.AspNetCore.Filters/Examples/ResponseExample.cs#L48

Which defaults to what you have now, but allows user overriding it.

**Comment by CumpsD** [comment]
Another option:

`AddXmlDataContractSerializerFormatters` just leads to `XmlDataContractSerializerOutputFormatter` being added, which is a subclass of `TextOutputFormatter`, just like `XmlSerializerOutputFormatter` (Which pretty much does what you have in `XmlSerialize`: https://github.com/aspnet/Mvc/blob/195a22d92c95445fabef3b17e67bee4aa75eff81/src/Microsoft.AspNetCore.Mvc.Formatters.Xml/XmlSerializerOutputFormatter.cs)

Maybe we can inject a `TextOutputFormatter` for xml?

**Comment by mattfrear** [comment]
I think we would use whichever JsonSerializer or XML serializer they are using to render responses. But I have had requests to allow custom examples in the past, i.e. render examples differently for requests (or responses).

This can be done using the `[SwaggerRequestExample] ` or `[SwaggerResponseExample]` attributes.

I can see this use case kind of making sense. You might for example want enums to render as strings in your request examples, as it makes for clearer documentation, even if your API itself doesn't accept strings. Personally it's an approach I disagree with - I think your examples should match what your API accepts / returns. As such I haven't used either of those attributes for many years, I use the "automatic annotations". It's an odd place to be in - having to support code I don't like and don't use, but can't get rid of because lots of other folks (might) use it, so I probably shouldn't introduce breaking changes 🤷‍♂️

**Comment by mattfrear** [comment]
But as for this issue, I think we should resolve whichever XML Serializer they have registered and use that.

**Comment by CumpsD** [comment]
I can try a PR, any suggestions you have as for the direction you want to see it?

**Comment by mattfrear** [comment]
> I can try a PR, any suggestions you have as for the direction you want to see it?

A PR would be welcome. I think we should figure out which XML Serializer their API is using to render their responses, and use the same one. The user shouldn't have to explicitly register it.

**Comment by CumpsD** [comment]
PR is coming up today :)

**Comment by CumpsD** [comment]
If you could have a look @mattfrear, it's in #137

**Comment by mattfrear** [comment]
I merged this PR accidentally so now I have reverted it, therefore this issue needs to be reopened.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.0.1
