### ISSUE TITLE
Use System.Text.Json

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [mattfrear/Swashbuckle.AspNetCore.Filters#174]
Looking through the required packages, I identified the swashbuckle.aspnetcore.filters library as having a dependency on newtonsoft.json.

I find this curious- as this dependency is not required by swashbuckle.aspnetcore, or swashbuckle.aspnetcore.annotations. 

As well- this is not a dependency required by .net core web api now either.

I would purpose removing this dependency to instead leverage the built-in system.text.json, rather then requiring the external newtonsoft.json package.

**Comment by XtremeOwnageDotCom** [comment]
Upon a bit more investigation- It appears newtonsoft is being leveraged due to this project targeting .net standard 2.0, which does not contain the system.text.json namespace. 

With this said- it may be beneficial to configure this project to be able to target multiple framework versions, to allow builds in either .net 5, or .net standard 2.1, where it would be possible to leverage the built-in framework features for deserialization.

**Comment by zolrath** [comment]
I'd love to see this change!

**Comment by mattfrear** [comment]
Yeah so to clarify, the examples will be serialized using whichever serializer your API uses. That work was done in https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/pull/159 .

I'll have a look into this when I get a chance.

**Comment by mattfrear** [comment]
I'm confused. If I remove the PackageReference to Newtonsoft.Json my solution still compiles. I'm not sure how, since 
`public class ExcludeObsoletePropertiesResolver : DefaultContractResolver`
and DefaultContractResolver lives in the Newtonsoft namespace.

FWIW the `ExcludeObsoletePropertiesResolver`  was introduced to support https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/98 which is an edge case. To use it you need to 
```csharp
services.AddControllers()
    .AddNewtonsoftJson(opt =>
    {
        opt.SerializerSettings.ContractResolver = new ExcludeObsoletePropertiesResolver(opt.SerializerSettings.ContractResolver);
    })
```
I wish I never introduced the `ExcludeObsoletePropertiesResolver` to support that edge case. I should have suggested he add it to his solution. If I remove it it means doing a major version bump.

I'll keep experimenting.

**Comment by mattfrear** [comment]
OK so I've been through this before... version 6.0.0 of this package didn't have a reference to Newtonsoft, and that could cause a problem, which was fixed in https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/pull/161

**Comment by XtremeOwnageDotCom** [comment]
Sounds like it just keeps coming back!

I think the only logical answer, is to remove the exclude Obsolete Properties filter! (And, add it as its own nuget package, with its own dependency on newtonsoft) 

Then everybody wins, right?

**Comment by mattfrear** [comment]
Removed Newtonsoft. Released in https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/7.0.2

**Comment by XtremeOwnageDotCom** [comment]
Excellent, Thanks @mattfrear !
