### ISSUE TITLE
How to have multiples request examples in endpoints with route params?

### ISSUE THREAD

**Issue by taniafri** [mattfrear/Swashbuckle.AspNetCore.Filters#213]
Hi,

I'm having troubles trying to have multiple request examples when the endpoint has route parameters. 

For instance, 
- api/v1/cars/{id}

Now i have,
![image](https://user-images.githubusercontent.com/114226784/191941192-b0d4b56f-1c7e-42c1-9070-7c298d890e6e.png)

but I would like,
![image](https://user-images.githubusercontent.com/114226784/191941387-61da8d1e-340b-46b7-85db-7844ab61fc50.png)

I'm using XML comments to define that id example as,
`/// <param name="id" example="3fa85f64-5717-4562-b3fc-2c963f66afa6">the Id of the a specific car</param>`

Is there a way to add multiple examples for route params?

Thanks

**Comment by mattfrear** [comment]
Using XML comments for examples is part of Swashbuckle.AspNetCore and not part of this library. I don't think it's possible to specify multiple examples that way - but you could try raise an issue over there.

You can use IMultipleExamplesProvider from this library, see the docs here: https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#how-to-use---multiple-examples

However, I don't think it will support using a plain old string very well. But it might? 
The intention of this library is to specify examples for request view models and responses.

**Comment by taniafri** [comment]
Ok, thanks for your answer.

**Comment by niteshsinghal85** [comment]
Hi @taniafri,

I have written short blog on same [topic ](https://medium.com/@niteshsinghal85/multiple-example-for-parameters-in-swagger-with-asp-net-core-c4f3aaf1ae9f). although it is not using xml comments but provides an alternative way of doing what you looking for.

Hope it helps.

**Comment by mattfrear** [comment]
Hi @niteshsinghal85 .
I wasn't aware of the `IParameterFilter` interface which you have used - nice one.

When I implemented this filter (for the old Swashbuckle.WebApi) I used an `IOperationFilter` because that seemed like the best fit at the time (IParameterFilter didn't exist then).

Personally, I would have stuck to using XML comments and come up with a way to use that - and then submitted a PR to Swashbuckle.AspNetCore. 

But kudos to you for implementing it the way you did.
