### ISSUE TITLE
 Unoptimized assembly detected: 'Swashbuckle.AspNetCore.Filters.dll'

### ISSUE THREAD

**Issue by fjmorel** [mattfrear/Swashbuckle.AspNetCore.Filters#231]
https://garcia.in/posts/2021/pitfalls-of-unoptimized-nuget-packages/

After building my API with that library, it revealed `Swashbuckle.AspNetCore.Filters` and `Swashbuckle.AspNetCore.Filters.Abstractions.` as not built in release mode.

**Comment by mattfrear** [comment]
OK, thanks for the heads up.
The performance impact of this would be nothing, because my package is only executed when someone downloads the swagger.json file.

However, compiler warnings aren't good, so I've fixed it and released it.

https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/7.0.8

**Comment by fjmorel** [comment]
Thanks!!
