### ISSUE TITLE
Keep default request body example while using custom examples

### ISSUE THREAD

**Issue by dionk** [mattfrear/Swashbuckle.AspNetCore.Filters#250]
`"Swashbuckle.AspNetCore.Filters" Version="8.0.2"`

Is there support for keeping the default request body example that is provided while using custom examples? By "default" example, I'm referring to the request body that has the complete model with example values (ex: string fields have value "string", bools = false, ints = 0, so on and so forth).

The request body that I am looking to provide examples for has many subclasses within it, and although we want to provide examples for the most common use cases, we are not providing examples for every use case. Because of this, we would like to keep the default request body available as a way for clients to see what fields can be used and what their values should be.

We can obviously just create a model with default values and add it to the GetExamples() method, but for a class that has many properties and child classes, it can become quite cumbersome.

**Comment by mattfrear** [comment]
I think that will happen out of the box. If you don't have an example for a specific class then the default "abc": "string" example should be used, although I haven't tried it - I usually don't use inheritance with my models.

**Comment by dionk** [comment]
Yes you're correct. If you don't have an example then the default will show. However, I'm trying to have both display. The full sample, as well as my custom example. 
So, lets say I have a class with two properties, string A and int B.

I want to have one example that shows
`
{
   "A": "string",
   "B": 0
}
`

as well as a custom
`
{
   "A": "my custom string"
   "B": 123456789
}
`

**Comment by mattfrear** [comment]
I don't know how the "default" examples are generated. They're not in the swagger.json (are they?), so they must be generated by [Swagger-UI](https://github.com/swagger-api/swagger-ui) for display.

You want to display 2 examples for every request - the default one, and your custom one.
You could do this by using IMultipleExamplesProvider, which allows you to display more than one example, like so:

![image](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/assets/169179/c13aaab7-4bf0-418c-817e-ffa94b97229d)

However, you would have to generate the default example yourself. That should be possible to do via reflection.

I'm gonna close this issue, because there's nothing for me to fix here.
