### ISSUE TITLE
Enable support for other mime types besides application/json

### ISSUE THREAD

**Issue by TheBels** [mattfrear/Swashbuckle.AspNetCore.Filters#43]
I am using Swashbuckle.AspNetCore v2.4.0 and Swashbuckle.AspNetCore.Examples v 2.9.0.

As I understand the [Open API v2.0 spec](https://swagger.io/docs/specification/2-0/adding-examples/) for examples, the examples should include the mime-type. Per [ExamplesOperationFilter](https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/blob/9eb6b006d4ce5e65f829c5944a15ada8d6885b82/src/Swashbuckle.AspNetCore.Examples/Examples/ExamplesOperationFilter.cs#L133) the mime type is being given as `application/json`.

This works for JSON responses; however, what if you have a response mime type of `text/csv`? The Open API spec link above has an example with two mime types: JSON and text.

I tried adding `[Produces("text/csv")]` to my action, as well as the attribute `[SwaggerResponse(200, typeof(string))]`. However it doesn't seem to pick up that mime type for the example.

Specifically, this is the swagger YAML:
![example-json](https://user-images.githubusercontent.com/12475792/39603274-c4f7277a-4ef5-11e8-812c-cc2fd17223bd.png)

This is how swagger-ui renders it:
![example-swagger-ui-json](https://user-images.githubusercontent.com/12475792/39603275-c6f0d5ee-4ef5-11e8-95a6-98efe3e72f53.png)

And this is what I would expect/want based off the `Produces` attribute:
![example-text png](https://user-images.githubusercontent.com/12475792/39603276-c88fa5e2-4ef5-11e8-8972-cb82c841541e.png)

Is it possible to use a mime-type other than JSON? Thanks!

**Comment by mattfrear** [comment]
I don't think that your usage of [Produces] is correct here, or maybe it's not enough for Swashbuckle.

I think what you need is to get the text/csv type listed in the `produces` section of the response:
![image](https://user-images.githubusercontent.com/169179/43003267-d5cacae6-8c23-11e8-9ae3-53d0c6bb26e9.png)

I don't know how you would do this. You might need to write your own custom `IOperationFilter` to do that.

But you're correct, even then my libary only supports JSON. There has been some small demand for me to support XML, which I am considering doing, but CSV you're the first person to ask for, so due to the small demand I'm not going to implement it (sorry). You are welcome to duplicate my `ExamplesOperationFilter` and customize it for your own CSV needs.

**Comment by TheBels** [comment]
Hi @mattfrear  - understood. Thanks for the reply and understood on not making the change.

**Comment by mattfrear** [comment]
CSV is now implemented.

https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/7.0.4
