### ISSUE TITLE
SwaggerRequestExample same Request Object overrides previous one

### ISSUE THREAD

**Issue by Exerlol** [mattfrear/Swashbuckle.AspNetCore.Filters#45]
Hello guys,
I'm using Swagger with c#, and here's an issue i'm currently facing, im using -
`[SwaggerRequestExample(typeof(RequestType1),typeof(RequestType1Example))]` and 
`[SwaggerRequestExample(typeof(RequestType1),typeof(RequestType2Example))]`  on two of my ActionMethods...

Where for example models are: 
```
public class RequestType1{
  public int Id {get;set;}
  public int Name {get;set;}
  public int Surname {get;set;}
}
public class RequestType1Example : IExamplesProvider{
 public object GetExamples()
        {
            return new RequestType1
            {
                  Id = 1, 
                  Name = "Test Name"
            }
        }
}

public class RequestType1Example : IExamplesProvider{
 public object GetExamples()
        {
            return new RequestType1
            {
                  Id = 1, 
                  Surname = "Test Surname"
            }
        }
}
```

Problem is that in Swagger UI in both APIs - example is same.

```
Example Value : 
{
  "Id": "1",
  "Surname":"Test Surname"
}

```
Is there any workaround on this? Or could i specify some kind of attribute to make swagger show different examples for both APIs? Thanks in advance

**Comment by mattfrear** [comment]
Hi,

Quick answer - that is a known issue, and is listed under the Known Issues on the Readme.

There could be a workaround for it which I will try to describe later when I get a chance.

**Comment by Exerlol** [comment]
Hey @mattfrear, thank you for your quick reply to my question... Also thanks in advance for providing workaround in future :)  Cheers

**Comment by mattfrear** [comment]
OK so let me try and describe why this is happening and how to possibly fix it.

If you look at the swagger.json, at the end of the document is `/definitions` and then each Request object is in there. My filter populates the `example` property.

Although you are using the same `RequestType1` on two actions, there is only one `RequestType1` defined in the `/definitions` thus there's only one `example` property.

However, there's another property that could be set instead. Each api endpoint is defined in the `/paths`, and each path has a `parameters` property, which has a schema, which can have an example property. So I could make some code changes to set this property.

**Comment by mattfrear** [comment]
A workaround you could do is to have a different class for each of your request types, e.g.
```csharp
public class RequestType2 : RequestType1
{
}
```

**Comment by Exerlol** [comment]
@mattfrear Sure I think i'll do that till this known issue is fixed, thank you very much for your time and help once again :)

**Comment by mattfrear** [comment]
I've had a crack at setting the `paths/parameters/schema/example` property I mentioned in my last comment.

Swagger-UI ignores it if there is a `/definitions` for the given schema object though - Swagger-UI always uses the example defined there, even if there isn't one. The only time it seems to display the `paths/parameters/schema/example` example is if there is nothing for that schema in the `/definitions`, which is what happens in my test project with `Dictionary<T>`.

So although the swagger.json looks correct - i.e. it has two different examples defined for the same `RequestType1`, only one of the examples is displayed in the Swagger-UI page. Thus, the Known Issue cannot be fixed.

I will leave this change in, because at least the swagger.json looks correct IMO.
