### ISSUE TITLE
Display Enums with a description

### ISSUE THREAD

**Issue by veler** [mattfrear/Swashbuckle.AspNetCore.Filters#52]
Greetings :)

With the implementation of `opt.DescribeAllEnumsAsStrings();`, we can display an enumeration's string as below : 

![capture](https://user-images.githubusercontent.com/3747805/42986437-dc2b2558-8bf5-11e8-8fa9-c627066c2995.PNG)

With the enum declared like this : 

```csharp
public enum EnumTest
{
    [Description("This is the Food value")]
    Foo = 1,

    Bar = 2,

    Boo = 3
}
```

I would like to do two suggestions here : 

1. Being able to render the Description attribute, which works fine in class properties, but doesn't work for enums.
2. When showing enum's strings, being able to still display the numeric value associated (1, 2 and 3 in this example). The reason why is that, in the case of what we are doing in the project I'm working on, ours consumers must enter a numeric value to make a choice (which corresponds to something in the Enum). We're looking for a way to associate the numeric value to a descriptive text, so the consumer knows which does what. We actually don't want him to send text.

Could it be something interesting enough to be implemented in a nearly future?

Thanks in advance :)

**Comment by veler** [comment]
OK, I just discovered the "EnumMember" attribute. But the second issue is still persistant to me.

**Comment by mattfrear** [comment]
If you use enums, the client will always be able to send text and MVC model binding will bind it for you to a value. So if you don't want them to send text, you probably shouldn't use an enum.

Maybe you should just take an int instead of an enum, and then use the [Description] property (or the Swashbuckle XML comments) to describe what are the valid values. And add a validator to check the values.

**Comment by veler** [comment]
Sounds good, thanks :)
