### ISSUE TITLE
Example for GET request query string parameters

### ISSUE THREAD

**Issue by m-demydiuk** [mattfrear/Swashbuckle.AspNetCore.Filters#66]
Hello.

I have `GET` request with 2 query string parameters `From` and `To`. I created request example like:
```
public class RequestExample : IExamplesProvider<Request>
    {
        public Request GetExamples()
        {
            return new Request
            {
                From = "USD",
                To = "AUD"
            };
        }
    }
```

But I do not see this example in the swagger. Instead I only see 2 input fields in the UI. Is it possible to show request example for query params?

Thanks in advance!

**Comment by mattfrear** [comment]
Hi, no it’s not possible for GETs. 

Matt

**Comment by mattfrear** [comment]
Thank you for raising the issue, I have added it to the list of Known issues in the Readme.

**Comment by spottedmahn** [comment]
Hi @mattfrear 👋 - can you expand upon:

>Hi, no it’s not possible for `GET`s.

Where is the limitation?

**Comment by spottedmahn** [comment]
And there must be a workaround 🤔?

**Comment by mattfrear** [comment]
Off the top of my head, I think you can set an example for a parameter in a get, and it will be there in the swagger JSON, but swagger-ui will not display it. (I think, but I'm not sure, need to check that)

Matt

Sent from my phone

**Comment by mattfrear** [comment]
> Off the top of my head, I think you can set an example for a parameter in a get, and it will be there in the swagger JSON, but swagger-ui will not display it. (I think, but I'm not sure, need to check that)

OK, I've dug a bit deeper, and what I said earlier was incorrect. The limitation for request examples is that examples can only be given for parameters that are in the request body (i.e. not in the query string). This is because the Swagger 2.0 spec says that:

> If in is "body":

> Field Name | Type | Description
> -- | -- | --
> schema | Schema Object | Required. The schema defining the type used for the body parameter.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject

**Comment by lonix1** [comment]
@spottedmahn I assume you found no workaround / hack / custom javascript / etc.?

**Comment by spottedmahn** [comment]
I didn't, sorry.  @lonix1

**Comment by dawu415** [comment]
Will there be any upcoming work to get examples in for Get Request parameters?  I was looking at the OAI 3.0.1 and it seems to show that support for examples in parameters is available

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#exampleObject

**Comment by mattfrear** [comment]
Good spotting @dawu415 . I'll have a look into it. It would be great to have examples on GET parameters.

**Comment by mattfrear** [comment]
Just had a quick play and it works 😀

![image](https://user-images.githubusercontent.com/169179/79621729-88cdec00-8168-11ea-8e50-28f5caf1aab0.png)

I'll need to tidy this up, add unit tests etc. This will be a great addition once it's ready.

**Comment by mattfrear** [comment]
OK so I started implementing this, and I remembered that querystring and route parameters can only be primitive types.

Therefore an IExamplesProvider would look something like:
```csharp
    public class PersonIdExample : IExamplesProvider<int>
    {
        public int GetExamples()
        {
            return 99;
        }
    }
```

To me that rules out using this with "automatic annotation", because every time you have an `int` as a parameter in any of your controller methods, the example of 99 would be used.

So then I thought, OK, we're only gonna use this with ye olde `[SwaggerRequestExample]` attribute (which I haven't used in years). It has this signature:
```csharp
public SwaggerRequestExampleAttribute(
    Type requestType, 
    Type examplesProviderType, 
    Type contractResolver = null, 
    Type jsonConverter = null)
```
And then I thought, well, that's not really gonna work here because if you had multiple of the same type and wanted different examples, e.g.
```csharp
[SwaggerRequestExample(typeof(int), typeof(IdExample))]
[SwaggerRequestExample(typeof(int), typeof(PersonIdExample))]
public PersonResponse GetPerson(int id, int age)
```
It wouldn't work, because both parameters are of type `int` (I think the example generated by the first attribute, IdExample would be used for both parameters). So then I thought well maybe I need to add yet another parameter to `SwaggerRequestExampleAttribute`, e.g.
```csharp
public SwaggerRequestExampleAttribute(
    Type requestType, 
    Type examplesProviderType, 
    Type contractResolver = null, 
    Type jsonConverter = null,
    string parameterName)
```
So that you could differentiate between the two `int` parameters above and have a different `IExamplesProvider` for each of them:
```csharp
[SwaggerRequestExample(typeof(int), typeof(IdExample), parameterName:"id")]
[SwaggerRequestExample(typeof(int), typeof(PersonIdExample), parameterName: "personId")]
public PersonResponse GetPerson(int id, int age)
```
And then I thought, wth, why not just create another attribute, e.g.
```csharp
public SwaggerParameterExampleAttribute(
    string parameterName,
    string example)
```
which would be much easier to use that `SwaggerRequestExampleAttribute`.
```csharp
[SwaggerParameterExample("id", "1")]
[SwaggerParameterExample("age", "23")]
public PersonResponse GetPerson(int id, int age)
```
So I started implementing that, and then I thought, hang on, doesn't Swashbuckle.AspNetCore have example generation built in? So I started looking at that, and then thought, ah this would be a better fit in Swashbuckle.AspNetCore. So I went and added it there and created a pull request https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1629. 

Usage:
```csharp
/// <param name="id" example="123">The product id</param>
public Product GetById(int id)
```
If the PR doesn't get accepted then I'll finish my `SwaggerParameterExampleAttribute`.

And that was how I spent 4 hours on a Sunday.

**Comment by dawu415** [comment]
Nice.

How would it work for binding request models?   Do the incoming request parameters still get mapped as if it were all individual parameters to a Get request?

e.g.   

```C#
Route[...]
public PersonResponse GetPerson([FromRoute]Person p)
```

where Person is a class like this.

```C#
public class Person 
{
     [Required]
     int Id
     [Required]
     int age
     ...  
}
```

**Comment by mattfrear** [comment]
> Route[...]
> public PersonResponse GetPerson([FromRoute]Person p)

Is that possible? To put [FromRoute] in front of a reference type? Please paste a working example as I've never seen it done.

**Comment by dawu415** [comment]
@mattfrear Here is a sample: https://github.com/dawu415/dotnetcore-webapi-sample
```C#
        // e.g. https://localhost:5001/weatherforecast/AU/MEL/1/2/2020
        [HttpGet]
        [Route("{country}/{city}/{day}/{month}/{year}")]
        public string Get([FromRoute]WeatherRequest wr)
        {
            return JsonSerializer.Serialize(wr);
        }
```
with WeatherRequest defined as 
```C#
using System.ComponentModel.DataAnnotations;

namespace sample.Models 
    {
    public class WeatherRequest {
        [Required]
        public string country { get; set;}
        [Required]
        public string city { get; set; }
        [Required]
        public int day { get; set; }
        [Required]
        public int month { get; set; }
        [Required]
        public int year { get; set; }
    }
}
```


You can see this in the browser e.g.  https://localhost:5001/weatherforecast/AU/MEL/1/2/2020
The controller is in `/Controllers` and the WeatherRequest model is in `/Models`

**Comment by mattfrear** [comment]
@dawu415 thanks for the sample. I didn't know you could do that with `[FromRoute]`. 

It's not something my example generation supports, and to be honest it seems like an edge case and is not something I'm going to spend time implementing, as I'm not going to use it myself.

I opened up your solution and I did try adding XML examples, as specified on Swashbuckle.AspNetCore's readme:
```csharp
    public class WeatherRequest {
        /// <summary>
        /// The country
        /// <example>AU</example>
        /// </summary>
        [Required]
        public string country { get; set;}
```
And I thought that maybe the examples would appear in the request, but it didn't work:
![image](https://user-images.githubusercontent.com/169179/79841655-d74ee500-840b-11ea-91dc-3b29b4a7d898.png)

So I think that is a bug to be raised against Swashbuckle.AspNetCore.

**Comment by mattfrear** [comment]
> So I went and added it there and created a pull request Swashbuckle.AspNetCore#1629.

My PR has been merged so this will be in the next release of Swashbuckle.AspNetCore. I'm closing this issue.

**Comment by mattfrear** [comment]
@dawu415 FYI I've edited my previous answer after I spotted my mistake and got it working.

**Comment by spottedmahn** [comment]
>My PR has been merged so this will be in the next release of Swashbuckle.AspNetCore

thanks @mattfrear 😊🤝
