### ISSUE TITLE
[Feature Request] Respect inherited AuthorizeAttribute

### ISSUE THREAD

**Issue by lonix1** [mattfrear/Swashbuckle.AspNetCore.Filters#93]
All my controllers and actions are [secure by default](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.2#require-authenticated-users) - so I don't explicitly decorate any of them with `[Authorize]`. This is a very common practice.

That means `AppendAuthorizeToSummaryOperationFilter` doesn't work, because it looks for the `[Authorize]` on controllers/actions directly, and doesn't consider inherited attributes.

**Comment by Kizmar** [comment]
Any update on this getting some attention?

**Comment by mattfrear** [comment]
I'm writing this from the middle of a 12 hour flight and am offline, so I can't see what the original request was... But if you're applying the Authorize attribute to all of your actions via some global middleware or filter or somesuch, then you don't need to use my library at all. You can use Swashbuckle's `c.AddSecurityRequirement`. The only downside of that is it will probably add the security requirement to actions which have `[AllowAnonymous]` when it shouldn't (I guess, haven't tested).

That might be good enough?

Matt

**Comment by lonix1** [comment]
Then we miss out on all the other goodies this library offers... :wink: Ideally the inherited attribute should be respected.

**Comment by mattfrear** [comment]
Heh you can still have the other "goodies" :-)

I just spent a couple of hours looking at this, and I don't know how to do it. There would need to be a way to find out what global filters have been registered, and I don't know how to do that in ASP.NET Core. There probably is a way, but I don't know how to do it.

This old blog post (and the GitHub code) hints at a way to do this with the ASP.NET MVC (not Core) https://haacked.com/archive/2011/08/10/writing-an-asp-net-mvc-controller-inspector.aspx/

So I'll close this ticket for now as I don't know how to do it.

I just now thought of an alternative... you could write your own filter to add Swagger security requirements to every action, except for those with `[AllowAnonymous]`. In fact I could have done that quicker than the time I just spent googling how to find out in ASP.NET Core how to find out which filters have been registered. I'm not going to write that filter though because I have no need, I only write filters for something that _I_ need on my projects.

Oh all right then here's some untested code which might work:
```
    public class AddSecurityToAllOperationsFilter : IOperationFilter
    {
        public void Apply(Operation operation, OperationFilterContext context)
        {
            if (context.GetControllerAndActionAttributes<AllowAnonymousAttribute>().Any())
            {
                return;
            }

            operation.Security = new List<IDictionary<string, IEnumerable<string>>>
                {
                    new Dictionary<string, IEnumerable<string>>
                    {
                        { "oauth2", Enumerable.Empty<string>() }
                    }
                };
        }
    }
```

You'd need to copy the `GetControllerAndActionAttributes` from my code here https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/master/src/Swashbuckle.AspNetCore.Filters/Extensions/OperationFilterContextExtensions.cs

**Comment by lonix1** [comment]
Thanks for looking into this. It's a pity it can't be easily done, I thought it was simple but I suppose I was wrong.

@Kizmar Let us know how you eventually tackle this problem, I'll do the same.

**Comment by lonix1** [comment]
I don't know the internals of you code, so I may be wrong here.

Is it not just a matter of something like:

````
typeof(FooController).GetCustomAttributes(inherit:true)
````

That will yield the attributes on the base class, which should include `AuthorizeAttribute`.

**Comment by mattfrear** [comment]
> Is it not just a matter of something like:
> 
> ```cs
> typeof(FooController).GetCustomAttributes(inherit:true)
> ```
> 
> That will yield the attributes on the base class, which should include `AuthorizeAttribute`.

I don't think that will work, because you're applying a global AuthorizeFilter, so the attribute wouldn't be there.

**Comment by lonix1** [comment]
Aaah, I now understand the problem! :smile:

**Comment by lonix1** [comment]
Aaah, I now understand the problem! :smile: 

There is a compromise solution, which is instead of using a filter like that link shows, we can apply `[Authorize]` onto a base controller class. And then that filter will be discoverable.

For @Kizmar and the others who need this functionality, would that approach be "good enough"? I'm happy with it but maybe I'm overlooking something. If we can get consensus on the solution, then maybe we can think make it happen.

**Comment by Kizmar** [comment]
Unfortunately that won't work in my case. We have several micro-services that would have to be refactored in order to support the base class approach vs. adding global filters in `Startup.cs`. I'll copy the source into one of the projects and see if I can find a way to make this work.

**Comment by mattfrear** [comment]
I'll reiterate that if you're not using `[AllowAnonymous]` on your controllers then you don't need any filter and can just use `AddSecurityRequirement`

**Comment by lonix1** [comment]
Still a nuisance after all this time, to decorate every controller (it's easy to forget, too). I added a [PR](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/pull/196) to solve this using the above discussed approach.

**Comment by mattfrear** [comment]
I just tested `[Authorize]` on a base class, and it already works fine:

```csharp
    [Route("api/[controller]")]
    public class BlahController : BaseController
    {
        [HttpGet]
        public IActionResult Matt()
        {
            return View();
        }
    }

    [Authorize]
    public class BaseController : Controller
    {
    }
```

![image](https://user-images.githubusercontent.com/169179/169929434-ca24245e-e87e-456a-b16e-64fb94458483.png)

I have added a unit test which also proves this is currently working.
