### ISSUE TITLE
IExamplesProvider doesn't respect IgnoreObsoleteProperties

### ISSUE THREAD

**Issue by effyteva** [mattfrear/Swashbuckle.AspNetCore.Filters#98]
Hi,

When using IExamplesProvider, the IgnoreObsoleteProperties is ignored, rendering an example with properties that have already been removed (yet weren't deleted) from the API.
Could this perhaps be fixed?

Thank you,
Effy

**Comment by mattfrear** [comment]
I don't know what IgnoreObsoleteProperties is, can you provide an example?

**Comment by effyteva** [comment]
Sure, it's documented here:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/2b171c0fc6efe40f3a29a45c48d6b01221a0c214/README.md
Under "Omit Obsolete Operations and/or Schema Properties"

**Comment by mattfrear** [comment]
Oh OK that's cool, I didn't know about that.

**Comment by mattfrear** [comment]
I've just had a look at this and I have a few unknowns:
1. `IgnoreObsoleteProperties` is a property of `SchemaGeneratorOptions`, and I don't know how I can access that in my ExamplesOperationFilter.Apply method: `public void Apply(OpenApiOperation operation, OperationFilterContext context)`. I'm given an OperationFilterContext but I'm not given a SchemaGeneratorOptions. So that's the first hurdle to overcome.
2. I don't know how to configure JSON.NET to omit `[Obsolete]` properties. Maybe there's an option in the SerializerSettings but I can't see it.

I'm going to close this issue as I don't know how to fix it. If someone else can figure out the 2 hurdles above then we can re-open and fix it.

**Comment by mattfrear** [comment]
Well no sooner had a written the above reply than I figured out the first unknown. I can inject an `IOptions<SchemaGeneratorOptions>` into my ExamplesOperationFilter's constructor, like so:
```public ExamplesOperationFilter(
            IServiceProvider serviceProvider,
            RequestExample requestExample,
            ResponseExample responseExample,
            IOptions<SchemaGeneratorOptions> optionsAccessor)
```
Reopening...

**Comment by mattfrear** [comment]
As for the second unknown, https://stackoverflow.com/questions/56685266/newtonsoft-json-net-do-not-serialize-obsolete-property

**Comment by mattfrear** [comment]
Hi again

Thanks for the bug report. I have released a fix for this https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.0.0-rc7

**Comment by effyteva** [comment]
Amazon, thank you,
Waiting for the final release!

**Comment by mattfrear** [comment]
The final release is dependent on when Swashbuckle.AspNetCore 5.0 will be released, but the author of that package hasn't given any hints as to when that will be.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/975

You might as well just install the rc version.

**Comment by mattfrear** [comment]
Lots of people have requested that I remove the Newtonsoft.Json dependency from this solution, so I have decided to remove the ExcludeObsoletePropertiesResolver. If you need this functionality you can copy the file from here into your own solution:

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/v6.0.1/src/Swashbuckle.AspNetCore.Filters/Examples/ExcludeObsoletePropertiesResolver.cs

You need to install it like:
```csharp
services.AddControllers()
    .AddNewtonsoftJson(opt =>
    {
        opt.SerializerSettings.ContractResolver = new ExcludeObsoletePropertiesResolver(opt.SerializerSettings.ContractResolver);
    })
```
